import json

from typing import Annotated

from fastapi import APIRouter, Path, Query

from backend.app.admin.schema.token import GetTokenDetail
from backend.common.enums import StatusType
from backend.common.response.response_schema import ResponseModel, ResponseSchemaModel, response_base
from backend.common.security.jwt import DependsSuperUser, jwt_decode, revoke_token
from backend.core.conf import settings
from backend.database.redis import redis_client

router = APIRouter()


@router.get('', summary='Get online users', dependencies=[DependsSuperUser])
async def get_sessions(
    username: Annotated[str | None, Query(description='Username')] = None,
) -> ResponseSchemaModel[list[GetTokenDetail]]:
    token_keys = await redis_client.get_prefix(f'{settings.TOKEN_REDIS_PREFIX}:*')
    online_clients = await redis_client.smembers(settings.TOKEN_ONLINE_REDIS_PREFIX)
    data: list[GetTokenDetail] = []
    if not token_keys:
        return response_base.success(data=data)

    def append_token_detail() -> None:
        data.append(
            token_detail.model_copy(
                update={
                   'username': extra_info.get('username', 'unknown'),
                    'nickname': extra_info.get('nickname', 'unknown'),
                    'ip': extra_info.get('ip', 'unknown'),
                    'os': extra_info.get('os', 'unknown'),
                    'browser': extra_info.get('browser', 'unknown'),
                    'device': extra_info.get('device', 'unknown'),
                    'last_login_time': extra_info.get('last_login_time', 'unknown'),
                },
            ),
        )

    token_values = await redis_client.mget(*token_keys)
    token_details: list[GetTokenDetail] = []
    extra_info_keys: list[str] = []
    for token in token_values:
        if not token:
            continue
        token_payload = jwt_decode(token)
        user_id = token_payload.user_id
        session_uuid = token_payload.session_uuid
        token_detail = GetTokenDetail(
            id=user_id,
            session_uuid=session_uuid,
            username='Unknown',
            nickname='Unknown',
            ip='Unknown',
            os='Unknown',
            browser='Unknown',
            device='Unknown',
            status=StatusType.enable if session_uuid in online_clients else StatusType.disable,
            last_login_time='Unknown',
            expire_time=token_payload.expire_time,
        )
        token_details.append(token_detail)
        extra_info_keys.append(f'{settings.TOKEN_EXTRA_INFO_REDIS_PREFIX}:{user_id}:{session_uuid}')

    extra_infos = await redis_client.mget(*extra_info_keys) if extra_info_keys else []
    for token_detail, extra_info in zip(token_details, extra_infos, strict=True):
        if extra_info:
            extra_info = json.loads(extra_info)
            # Exclude tokens generated by swagger login
            if extra_info.get('swagger') is None:
                if username is not None:
                    if username == extra_info.get('username'):
                        append_token_detail()
                else:
                    append_token_detail()
        else:
            data.append(token_detail)
    return response_base.success(data=data)


@router.delete(
    '/{pk}',
    summary='Forced offline',
    dependencies=[DependsSuperUser],
)
async def delete_session(
    pk: Annotated[int, Path(description='User ID')],
    session_uuid: Annotated[str, Query(description='Session UUID')],
) -> ResponseModel:
    await revoke_token(pk, session_uuid)
    return response_base.success()
